export const TOGGLE_APP_LAYOUT = "TOGGLE_APP_LAYOUT";
export const CHANGE_HEAD_TITLE = "CHANGE_HEAD_TITLE";
export const OPEN_POPUP = "OPEN_POPUP";
export const CLOSE_POPUP = "CLOSE_POPUP";

export const ADD_EDIT_ITEM = "ADD_EDIT_ITEM";
export const REMOVE_EDIT_ITEM = "REMOVE_EDIT_ITEM";

export const ADD_ROOM = "ADD_ROOM";
export const REMOVE_ROOM = "REMOVE_ROOM";
export const SELECT_ROOM = "SELECT_ROOM";
export const SELECT_TIME = "SELECT_TIME";
export const UPDATE_EVENTS = "UPDATE_EVENTS";
export const UPDATE_GENERAL_EVENTS = "UPDATE_GENERAL_EVENTS";
export const UPDATE_CHOOSEN_EVENTS_TYPE = "UPDATE_CHOOSEN_EVENTS_TYPE";
export const UPDATE_FOUNDED_HEARINGS = "UPDATE_FOUNDED_HEARINGS";
export const UPDATE_FOUNDED_HEARINGS_NUMBERS =
  "UPDATE_FOUNDED_HEARINGS_NUMBERS";
